name: My first Workflows 

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name : Checkout repo
              uses: actions/checkout@v4

            - name: List and read files
              run: | 
                echo "My First Github Action Job"
                ls -ltra
                cat README.md

            - name : Display ASCII Character 
              run : cowsay -f dragon " Run for Cover , I am a Dragon " >> dragon.txt
            
            # - name : List files
            #   run : ls

            # - name : Read Files 
            #   run : cat README.md 

