name: Generate ASCII Artwork

on: push

jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name : Install cowsay 
              run : sudo apt install cowsay -y 

            - name: Exwcute cowsay command 
              run : cowsay -f dragon " Run for Cover , I am a Dragon " >> dragon.txt

            - name : Upload Dragon text
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt 


    test_job_1 : 
        needs: build_job_1
        runs-on: ubuntu-latest
        steps : 
            - name: test for file existance
              run : grep -i "dragon" dragon.txt
         
            - name : Upload Dragon text
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file


    deploy_job_1 : 
        needs: test_job_1
        runs-on: ubuntu-latest
        steps : 
            - name : Upload Dragon text
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file

            - name : Read File 
              run : cat dragon.txt

            - name :  Deployed 
              run : echo "Deploying ... .. ."
