name: Matrix Configuration

on:
#   push:
  workflow_dispatch:

jobs:
    deploy:
      
      strategy:
        fail-fast: false 
        max-parallel: 2
        matrix:
          os: [ ubuntu-latest , windows-latest , ubuntu-22.04 ]
          images : [hello-world , alpine ]
          exclude:
            - images : alpine
              os: windows-latest
          include:
            - images : amd64/alpine
              os: ubuntu-latest
          

      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Images
        run: docker run ${{ matrix.images }}